version: '3.9'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: url_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  encode-service:
    build: ./encode-service
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: local
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/url_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

  decode-service:
    build: ./decode-service
    ports:
      - "8082:8082"
    depends_on:
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: local
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/url_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - encode-service
      - decode-service
    environment:
      ENCODE_PATH: http://encode-service:8081
      DECODE_PATH: http://decode-service:8082

volumes:
  pgdata:
