DB_URL: jdbc:postgresql://localhost:5432/encode_url_db
DB_USER: daniele
DB_PASSWORD: password12345

BASE_URL: localhost:8081

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true